apiVersion: v1
kind: Service
metadata:
  labels:
    app: theia-spring-boot
  name: theia-spring-boot
spec:
  type: NodePort
  selector:
    app: theia-spring-boot
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: theia-spring-boot
  name: theia-spring-boot
spec:
  replicas: 1
  selector:
   matchLabels:  
    app: theia-spring-boot
  template:
    metadata:
      labels:
        app: theia-spring-boot
    spec:
      containers:
        - name: theia-spring-boot
          image: theia-spring-boot
          imagePullPolicy: Never
          ports:
          - containerPort: 3000
          volumeMounts:
          - name: source
            mountPath: /home/project
        - name: git-sync
          image: k8s.gcr.io/git-sync:v3.0.1
          volumeMounts:
          - name: source
            mountPath: /tmp/git
          env:
          - name: GIT_SYNC_REPO
            value: https://github.com/spring-projects/spring-petclinic.git
          - name: GIT_SYNC_BRANCH
            value: master
          - name: GIT_SYNC_DEST
            value: git-sync
      volumes:
        - name: source
          emptyDir: {}
