resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
resources:
- name: docker-git
  type: git
  source:
    uri: git@github.com:spring-projects/sts4.git
    branch: {{branch}}
    username: kdvolder
    private_key: {{rsa_id}}
    paths:
    - concourse/docker
- name: sts4
  type: git
  source:
    uri: git@github.com:spring-projects/sts4.git
    branch: {{branch}}
    private_key: {{rsa_id}}
- name: s3-boot-properties-vsix
  type: s3
  source:
    bucket: {{s3_bucket}}
    access_key_id: {{s3_accesskey}}
    secret_access_key: {{s3_secretkey}}
    regexp: sts4/vscode-extensions/vscode-boot-properties-(.*).vsix
- name: s3-manifest-yaml-vsix
  type: s3
  source:
    bucket: {{s3_bucket}}
    access_key_id: {{s3_accesskey}}
    secret_access_key: {{s3_secretkey}}
    regexp: sts4/vscode-extensions/vscode-manifest-yaml-(.*).vsix
- name: slack-notification
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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
- name: docker-image
  type: docker-image
  source:
    username: {{docker_hub_username}}
    email: {{docker_hub_email}}
    password: {{docker_hub_password}}
    repository: kdvolder/sts4-build-env
jobs:
- name: build-docker-image
  serial: true
  plan:
  - get: docker-git
    trigger: true
  - put: docker-image
    params:
      build: docker-git/concourse/docker
    get_params: 
      skip_download: true
- name: build-vsix
  plan:
  - get: sts4
    trigger: true
  - task: build-vscode-extensions
    file: sts4/concourse/tasks/build-vscode-extensions.yml
    on_success:
      aggregate:
      - put: s3-manifest-yaml-vsix
        params: 
          file: vsix-files/vscode-manifest-yaml-*.vsix
      - put: s3-boot-properties-vsix
        params: 
          file: vsix-files/vscode-boot-properties-*.vsix
    on_failure:
      put: slack-notification
      params:
        channel: "@kdvolder"
        text: | 
           Concourse ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME} has failed!
