#An example for Andy
resources:
- name: version
  type: semver
  source:
    driver: git
    file: fancy-bundle
    uri: git@github.com/kdvolder/versions-repo
    branch: master 
- name: my-git
  type: git
  source:
    uri: git@github.com/kdvolder/test
    branch: master
- name: my-bundle
  type: s3
  source:
    bucket: my.bucket.spring.io
    access_key_id: {{s3_key}}
    secret_access_key: {{s3_secret}}
    regexp: snapshots/fancy-bundle-(.*).zip
jobs:
- name: build-it
  plan:
  - get: my-git
    trigger: true
  - task: build-it
    config:
      platform: linux
      inputs:
      - name: my-git
      outputs:
      - name: target
        path: my-git/target
      image_resource:
        type: docker-image
        source:
          repository: kdvolder/my-build-env
      run:
        path: my-git/scripts/build-iy.sh
  - put: my-bundle
    params:
      file: my-git/target/fancy-bundle-*.zip
- name: test-it
  plan: 
  - get: my-git
    passed:
    - build-it
  - get: my-bundle
    passed:
    - build-it
  - task: run-tests
    config:
      platform: linux
      inputs:
      - name: my-bundle
      image_resource:
        type: docker-image
        source:
          repository: kdvolder/my-build-env
      run:
        path: my-git/scripts/run-tests.sh
- name: publish-it
  plan: 
  - get: my-git
    passed:
    - test-it
  - get: my-bundle
    passed:
    - test-it
  - task: publish
    config:
      platform: linux
      inputs:
      - name: my-bundle
      image_resource:
        type: docker-image
        source:
          repository: kdvolder/my-build-env
      run:
        path: my-git/scripts/publish.sh
