inputs:
- name: sts4
- name: package_sources
- name: fatjar
outputs:
- name: out
platform: linux
image_resource:
  type: docker-image
  source:
    repository: kdvolder/sts4-build-env
run:
  path: sts4/concourse/tasks/build-atom-package.sh
