platform: linux
image_resource:
  type: docker-image
  source: 
    repository: kdvolder/sts4-build-env
inputs:
- name: sts4
outputs:
- name: out
run:
  path: sts4/concourse/tasks/create-rc-build-tag.sh
