---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: kdvolder/sts4-build-env

inputs:
- name: sts4

run:
  path: mvn
  args: ["clean", "package"]
  dir: sts4/vscode-extensions
