inputs:
- name: sts4
params:
  mirror_repo: https://github.com/pivotal/sts4-vscode-spring-boot-mirror
outputs:
- name: out
platform: linux
image_resource:
  type: docker-image
  source:
    repository: kdvolder/sts4-build-env
run:
  path: sts4/concourse/tasks/sync-mirror-repo.sh
